knp_paginator:
  page_range: 5
  default_options:
    sort_field_name: 'sort'
    sort_direction_name: 'direction'
    distinct: true
  template:
    pagination: '@KnpPaginator/Pagination/twitter_bootstrap_v4_pagination.html.twig'     # sliding pagination controls template
    sortable: '@KnpPaginator/Pagination/sortable_link.html.twig' # sort link template
    filtration: '@KnpPaginator/Pagination/filtration.html.twig'  # filters template